USE [master]
GO

/****** Object:  Database [Insurance]    Script Date: 26.03.2022 13:51:07 ******/
CREATE DATABASE [Insurance]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Insurance', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Insurance.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Insurance_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Insurance_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Insurance].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Insurance] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Insurance] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Insurance] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Insurance] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Insurance] SET ARITHABORT OFF 
GO

ALTER DATABASE [Insurance] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Insurance] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Insurance] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Insurance] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Insurance] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Insurance] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Insurance] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Insurance] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Insurance] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Insurance] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Insurance] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Insurance] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Insurance] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Insurance] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Insurance] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Insurance] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Insurance] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Insurance] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Insurance] SET  MULTI_USER 
GO

ALTER DATABASE [Insurance] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Insurance] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Insurance] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Insurance] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Insurance] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Insurance] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Insurance] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Insurance] SET  READ_WRITE 
GO

